import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import { Inter } from '@next/font/google';
import Image from 'next/image';
import osidevsito from '../public/osidevsito.jpg';
import port1 from '../public/port1.png';
import port2 from '../public/port2.png';
import port3 from '../public/port3.png';
import port4 from '../public/port4.png';
import port5 from '../public/port5.png';
import port6 from '../public/port6.png';
import { useState } from 'react';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Osiris Macias Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-800">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons">DevelopbyOsiris</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-xl"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Osiris Macias
            </h2>
            <h3 className="text-2xl py-2 md-text-3xl">Frontend Developer</h3>
            <p className="text-lg py-5 leading-8  text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Likable, dedicated and quick learner Frontend Developer with over
              1 year of experience in learning, creating and maintaining code.
              Fell free to reach me out and let's get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-20 py-3 text-gray-600 pb-3">
            <a
              target={'blank'}
              href={'https://www.linkedin.com/in/osiris-macias/'}
            >
              <AiFillLinkedin />
            </a>
            <a target={'blank'} href={'https://github.com/Mancosiris13'}>
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full  w-80 h-80 mt-20 max-w-xl mx-auto ">
            <Image
              src={osidevsito}
              className=" ml-auto mr-auto pt-20 md:h-95 md:w-95"
              objectFit="cover"
            />
          </div>
        </section>
        <section className="leading-8 text-center">
          <div>
            <h3 className="text-3xl py-1  p-10 md:text-4xl pt-10">Skills</h3>
            <p className="text-lg py-5 leading-8 text-gray-800  md:text-xl max-w-xl mx-auto dark:text-white">
              Since the beginning of my journey as a Frontend Developer, I have
              worked with several technologies such as:{' '}
            </p>
          </div>
          <div className=" rounded-xl  p-8 text-lg    items-center font-burtons leading-8  md:text-xl">
            <div className=" inline-block">
              <ul>
                <li>
                  <span className="px-5 ">JavaScript</span>
                </li>
                <li>
                  <span className="px-5">React.Js</span>
                </li>
                <li>
                  <span className="px-5">React Hooks</span>
                </li>
                <li>
                  <span className="px-5">Web Services</span>
                </li>
                <li>
                  <span className="px-5">Next.Js</span>
                </li>
                <li>
                  <span className="px-5">Responsive CSS</span>
                </li>
                <li>
                  <span className="px-5">Sass</span>
                </li>
              </ul>
            </div>
            <div className=" inline-block">
              <ul>
                <li>
                  <span className="px-5">CSS Frameworks</span>
                </li>
                <li>
                  <span className="px-5">HTTP</span>
                </li>
                <li>
                  <span className="px-5">Postman</span>
                </li>
                <li>
                  <span className="px-5">MySQL</span>
                </li>
                <li>
                  <span className="px-5">AWS</span>
                </li>
                <li>
                  <span className="px-5">Node.Js</span>
                </li>
                <li>
                  <span className="px-5">Git/Github</span>
                </li>
              </ul>
            </div>
          </div>
        </section>
        <section className="leading-8 text-center">
          <div>
            <h3 className="text-3xl py-1  p-10 md:text-4xl pt-10">
              {' '}
              Portofolio
            </h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              In this section is showed my work developed with different
              technologies, from landing pages, to responsive desing, use of
              hooks, data manipulation, web services, advanced css , etc.
            </p>
          </div>
          <div className=" flex flex-col gap-10 py-10 lg:flex-row lg: flex-wrap">
            <div className="basis-1/3 flex-1 shadow-xl">
              <Image
                src={port3}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={port4}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={port1}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={port2}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={port5}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={port6}
                className="rounded-lg object-cover"
                width={'100%'}
                height={'100%'}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
